### ISSUE TITLE
或许可以考虑迁移到Hugging Face？

### ISSUE THREAD

**Issue by xinyangli** [openwhu/OpenWHU#106]
[Hugging Face](https://huggingface.co) 现在经常被用于共享预训练的深度学习模型、数据集。一些优势：

- Hugging Face能够提供单文件下载、上传。
- 暂时没有被墙。
- 使用Git lfs，将现有项目迁移过去的成本不高。
- 不需要自己维护Hosting服务。

不过可能需要具体看一下他们的使用条款是不是支持这样的使用方式。

**Comment by Crescentm** [comment]
We provide Services in the field of machine learning, here is the list:

**Open-Source Libraries: including Transformers, Datasets and Tokenizers**

Hugging Face public Hub: where you can build, benchmark, share, version and deploy Models, Datasets and Machine Learning Applications accessible by all Users

Hugging Face private Hub: where you can build, benchmark, share, version and deploy Models, Datasets and Machine Learning Applications, that are only accessible by You or your Organization(s)

Inference API Service: where you or your organization(s) can run inference via application programming interface on machine learning models publicly or privately hosted on our Model Hub

AutoTrain premium Service: create state of the art Models from your own training data, everything being automatically hosted privately on the Model Hub. You can then share them publicly and/or serve them through the Inference API Service for example.

Expert Acceleration Program: get Premium Support on the use of our open source and all our services and/or products.

Infinity Service: deploy end-to-end optimized inference pipelines for state of the art Transformers Models.

Hardware Partner Program: access State of the Art hardware and hardware-specific machine learning optimization techniques for production performance.

Inference Endpoints: easily deploy machine learning models on dedicated, secure and autoscaling infrastructure

**Comment by xinyangli** [comment]
传在Datasets上应该不能算是违反了用户协议吧？

**Comment by Crescentm** [comment]
其实还有第一句话in the field of machine learning，OpenWHU也不是机器学习相关的项目吧
