### ISSUE TITLE
资源下载的问题

### ISSUE THREAD

**Issue by yeung66** [openwhu/OpenWHU#15]
在给出的主页中，点击资源链接进行下载会跳转到GitHub端，单个文件的下载还好，但如果是一个文件夹或者是多个文件批量下载就比较麻烦。
看了其它的相关的项目，大多是通过[DownGit](https://minhaskamal.github.io/DownGit/#/home)解决的。我们也可以在README中添加下载方式说明，甚至可以考虑主页中直接添加下载链接（参考中科大相关项目

**Comment by OpenWHU-D** [comment]
先添加到README 未来看能不能写个脚本自动生成
