### ISSUE TITLE
关于维护一个Unofficial版本的想法

### ISSUE THREAD

**Issue by Crescentm** [openwhu/OpenWHU#32]
通过分布式网络的方式维护一个Unofficial版本，降低入门门槛，~~以及维护一些其他东西~~

**Comment by yqwu905** [comment]
搭建一个镜像站?如果目标只是资源分发和下载的话我可以参与.如果是需要实现上传的话可能我的水平不够.
我的想法是建立一个类似于ftp服务器的网站,定期从github上来同步内容,也许可以方便下载

**Comment by Crescentm** [comment]
前者主要基于[Resilio Sync](https://www.resilio.com/individuals/)或者[微力同步](http://www.verysync.com/download.html)这些软件来做到像文件夹一样可拖拽式上传。

后者当然肯定会做一个类似于ftp的、内容基于github的下载网站，多半是在主页上进行改动。(顺便说一句项目的有些资源是在git-lfs上的，可能这些资料的下载链接需要手动修改)
