### ISSUE TITLE
QQ群加不了

### ISSUE THREAD

**Issue by karlMarx1818** [openwhu/OpenWHU#64]
1019979939群加不了
![image](https://user-images.githubusercontent.com/91475814/147486815-6a3222a5-a662-4369-9c90-cefde8b7ec33.png)

**Comment by yqwu905** [comment]
确实，拉个新群？ @Crescentm

**Comment by Crescentm** [comment]
目前**OpenWHU没有官方QQ群**（个人觉得管理起来太麻烦）
武大课程推荐群是和OpenWHU是合作关系，目前应该是群成员满了，待扩容就好了。

**Comment by leo314159** [comment]
或许可以建一个官方tg群🤔

**Comment by yqwu905** [comment]
> 或许可以建一个官方tg群🤔

这个可以有，但似乎门槛更高了(

**Comment by leo314159** [comment]
> > 或许可以建一个官方tg群🤔
> 
> 这个可以有，但似乎门槛更高了(

差不多吧，现在谁上github不用梯子捏（）

**Comment by Crescentm** [comment]
https://t.me/+M-q4hNSK955lNGNl
目前不知道为啥不能公开群组，先建一个

**Comment by Shelly-S** [comment]
> 

改hosts之后能看,不知道为什么push老是出错( )

**Comment by Crescentm** [comment]
隔壁群已经现已可以加入
