### ISSUE TITLE
求助，请问怎么样才能上传试卷？

### ISSUE THREAD

**Issue by Naza2300** [openwhu/OpenWHU#70]
如题，求助，请问各位小伙伴该如何才能上传试卷到文档里？本人是2021级的计算机留学生，想把资源分享给大家。麻烦各位帮忙，谢谢！

[2021学年第二学期《离散数学》期中考试 试卷A卷.pdf](https://github.com/openwhu/OpenWHU/files/8537000/2021.A.pdf)

**Comment by luzhixing12345** [comment]
可以在上方提pull request

**Comment by Crescentm** [comment]
通过邮件发送给openwhu@outlook.com即可。
已上传，感谢您的贡献
