### ISSUE TITLE
不建议放在GitHub上

### ISSUE THREAD

**Issue by lixianglong3210** [openwhu/OpenWHU#84]
国家信息安全

**Comment by lixianglong3210** [comment]
你可以使用国内的gitee，或者用hexo等自己搭建一个博客即可公开，也可以加入腾讯文档计划等国内社区

**Comment by karlMarx1818** [comment]
> 国家信息安全

上网不涉密，涉密不上网。一些考试题和ppt有啥信息安全的问题？放到网上就是公开了，国内国外，github gitee都一样。真有啥秘密内容压根九不会放网上

**Comment by chenxiex** [comment]
Public仓库本来就全部公开，没有保密问题。
如果是对github在国内的访问情况感到担忧，那么该问题与 #43 、 #82 重复了。
