### ISSUE TITLE
关于上传方式的问题

### ISSUE THREAD

**Issue by chenxiex** [openwhu/OpenWHU#86]
在下载站页面中提到可以将文件提交到upload文件夹来上传，然而在官网“上传”页面（[https://openwhu.github.io/upload/](url)）中没有提到这种方法。实际上我觉得这是门槛最低的提交方式，应该推广。

**Comment by Crescentm** [comment]
因为最终还是得手动更新到github上呀，不是特别方便

**Comment by Crescentm** [comment]
以及这个下载站的服务器不稳定（只买了一年），不保证长期提供服务。
